#5647
commit 640e659dfc36439523456cabf4f7c95af3bfe4c8
Author: mina <28566705+mina9999@users.noreply.github.com>
Date:   Thu Mar 31 16:05:42 2022 +0430

    [Modlog] Check if guild is unavailable

    fix for  AttributeError: 'NoneType' object has no attribute 'guild_permissions'